### ISSUE TITLE
Feedback for python - Get Dedicated Host Allocation

### ISSUE THREAD

**Issue by paulmcgrail** [softlayer/softlayer.github.io#100]
Feedback regarding: https://softlayer.github.io/python/getdedihostallocation/

This is great information, but a  key component is missing, where can the Dedicated Host ID be retrieved from?

I cannot currently retrieve the hardware/host ID for dedicated hosts...

Id for destination dedicated host for VSI migration
migrateGuest = client['SoftLayer_Virtual_Guest'].migrateDedicatedHost(**destinationHostId**, id=vsiId)

getAllocStats = client['SoftLayer_Virtual_DedicatedHost'].getAllocationStatus(id=**dedicatedHostId**)
pp(getAllocStats)

**Comment by greyhoundforty** [comment]
You can use the [SoftLayer_Account::getDedicatedHosts](http://sldn.softlayer.com/reference/services/softlayer_account/getdedicatedhosts) method to list the dedicated hosts on your account.

```
import SoftLayer
from pprint import pprint as pp

client = SoftLayer.Client()

dedicatedHosts = client['SoftLayer_Account'].getDedicatedHosts()
pp(dedicatedHosts)
```

**Comment by greyhoundforty** [comment]
I'll also update the examples to reflect how you get the host IDs.

**Comment by greyhoundforty** [comment]
Closing issue
