### ISSUE TITLE
Update Bluemix for AWS professionals page

### ISSUE THREAD

**Issue by chrisguz** [softlayer/softlayer.github.io#101]
Please update this page with proper branding (Bluemix to IBM Cloud) and verify that links work (note the first link "Bluemix."  Also verify currency of verbiage (example 20 data centers mentioned).   https://softlayer.github.io/tools/compareorator/

**Comment by allmightyspiff** [comment]
Finally got around to this. Bluemix should be IBM Cloud on that page now.
