### ISSUE TITLE
Formatting needs to be updated

### ISSUE THREAD

**Issue by cknabe** [softlayer/softlayer.github.io#110]
https://softlayer.github.io/reference/services/SoftLayer_Product_Order/placeOrder/

The examples are not easy to look at: 

> Server example

> This example includes a single bare metal server being ordered with monthly billing.
> 
> 
> Warning: the price ids provided below may be outdated or unavailable, so you will need to determine the available prices from the bare metal server [[SoftLayer_Product_Package/getAllObjects|packages]], which have a [[SoftLayer_Product_Package_Type (type)|package type]] of “‘BARE_METAL_CPU”’ or “‘BARE_METAL_CORE”‘. You can get a full list of [[SoftLayer_Product_Package_Type/getAllObjects|package types]] to see other potentially available server packages.
> 
> 
> SOAP-ENV:Header ns1:authenticate your username your api key /ns1:authenticate /SOAP-ENV:Header SOAP-ENV:Body ns1:placeOrder example.com server1 138124 142 58 22337 21189 876 57 55 21190 36381 21 22013 906 420 418 342 false /ns1:placeOrder /SOAP-ENV:Body /SOAP-ENV:Envelope 

Also some of the data shows up as URLs ^

**Comment by allmightyspiff** [comment]
Will be fixed internally as part of CORE-2186

**Comment by allmightyspiff** [comment]
That page should look much better now.
