### ISSUE TITLE
DataTypes on SoftLayer_Product_order goes nowhere

### ISSUE THREAD

**Issue by cknabe** [softlayer/softlayer.github.io#111]
https://softlayer.github.io/reference/services/SoftLayer_Product_Order/
I get a 404 when clicking DataTypes here ^

**Comment by allmightyspiff** [comment]
The system I use to build this site assumes every service has a datatype, which for Product_Order seems to not be the case.  Thanks for bringing it to my attention, but so far I haven't had to chance to really put a solution together.
