### ISSUE TITLE
Softlayer user permission link is broken

### ISSUE THREAD

**Issue by hkantare** [softlayer/softlayer.github.io#118]
We are not able to access below link
https://softlayer.github.io/reference/datatypes/Permissions

**Comment by allmightyspiff** [comment]
https://softlayer.github.io/reference/datatypes/SoftLayer_User_Customer_CustomerPermission_Permission/ is the page you are looking for. The whole list of services and datatypes that softlayer supports can be found here: https://softlayer.github.io/reference/softlayerapi/
