### ISSUE TITLE
jarteche/getting-started-user-data-and-post-provisioning-scripts needs to be updated

### ISSUE THREAD

**Issue by cknabe** [softlayer/softlayer.github.io#123]
When I navigate to https://softlayer.github.io/blog/jarteche/getting-started-user-data-and-post-provisioning-scripts/ it is hard to make heads or tails of what is going on in the document:

![image](https://user-images.githubusercontent.com/13582620/43719366-200dc374-9953-11e8-9142-c834253015da.png)

When I go to the original post via the waybackmachine, it is super easy to read. Customers should not have to use the waybackmachine to be able to understand content.

https://web.archive.org/web/20140902102637/https://sldn.softlayer.com/blog/jarteche/Getting-Started-User-Data-and-Post-Provisioning-Scripts

**Comment by allmightyspiff** [comment]
Updated. This page should be a bit easier to read now.
