### ISSUE TITLE
Problem with requestVdrContentUpdates

### ISSUE THREAD

**Issue by jensenbox** [softlayer/softlayer.github.io#125]
We are trying to move all our servers into the same bandwidth pool.

The API call is requestVdrContentUpdates on the SoftLayer_Network_Bandwidth_Version1_Allotment service with the parameters of:

`{'id': 1447299, 'virtualRack': {'id': 2458}}` as the "server" object being added and the pool id of 113902

We are using User ID 38190 and am now getting the following error:

`SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception): Unable to create a new object of type SoftLayer_Ticket_Advanced. Make sure the authentication method is correct.`

We had a few different dances with setting the correct permissions but now we think that we have all the perms set properly and are getting this error.

Here is our script in Python:

```
import os

import SoftLayer

if __name__ == "__main__":
    bandwidth_pool_id = 113902

    BASE_DIR = os.path.dirname(os.path.realpath(__file__))
    client = SoftLayer.create_client_from_env(config_file=os.path.join(BASE_DIR, 'softlayer.ini'))

    account_service = client['SoftLayer_Account']
    pool_service = client['SoftLayer_Network_Bandwidth_Version1_Allotment']

    server_mask = 'mask[id,virtualRack[id]]'

    servers = account_service.getHardware(mask=server_mask)

    for server in servers:

        current_bw_id = server['virtualRack']['id']

        if current_bw_id != bandwidth_pool_id:
            try:
                pool_service.requestVdrContentUpdates([server], [], [], [], id=bandwidth_pool_id)
            except SoftLayer.SoftLayerAPIError:
                print("Trying to requestVdrContentUpdates - adding %s to pool %s", server, bandwidth_pool_id)
                raise
```

**Comment by acamacho82** [comment]
The error "_Unable to create a new object of type SoftLayer_Ticket_Advanced_." means there are a missing permissions, I recommend to check if your user account has the following permissions, requestVdrContentUpdates worked for me after assigning them to my user:

- View Tickets
- Add Ticket
- Edit Tickets
- View All Tickets.
