### ISSUE TITLE
A malformed API call to order 2nd disk???

### ISSUE THREAD

**Issue by edwardstudy** [softlayer/softlayer.github.io#127]
Hi, 

We met an incorrect process to order 2nd disk. I ordered a VM with that 100GB. After that, I ordered a new 300GB to replace the previous 100GB one but, instead of that, this disk has been added, so you now have both disks(`/dev/xvdc`, `/dev/xvde`) which SL supports told me.

Currently, I used this API to create/replace 2nd disk:
```
https://api.softlayer.com/rest/v3.1/SoftLayer_Product_Order/placeOrder.json
Parameters: {"parameters":[{"complexType":"SoftLayer_Container_Product_Order_Virtual_Guest_Upgrade","packageId":46,"prices":[{"categories":[{"categoryCode":"guest_disk1","id":82}],"id":112911,"item":{"capacity":300,"description":"300 GB (LOCAL)"}}],"properties":[{"name":"MAINTENANCE_WINDOW","value":"2018-10-17T06:51:13Z"},{"name":"NOTE_GENERAL","value":"Upgrade instance configuration."}],"virtualGuests":[{"id":XXXXXXXX}]},false]}
```

When:
1. If this VSI has a 2nd_disk with the same capacity, SL returns an error to tell me this order exists.
2. If this VSI has a 2nd_disk with different capacity, SL orders new 2nd_disk and replaces it.

That's what I expect.

-------------------------

But in our production env, as I mentioned, I ordered a VM(41925715) to replace old 100GB and there were **2** disks from my end.

And I failed to reproduce this issue. SL supports replied this a malformed API call and suggested to open this issue to you. And I opened a ticket about it(https://control.softlayer.com/support/tickets/67079537 if you have access to look at backlog).

And please please please do not change API behavior before tell me. Because we really rely on this process currently to replace 2nd_disk. Any change might cause our production env fragile. 

Thank you.

**Comment by acamacho82** [comment]
I think the behavior you got is expected since you already added a second disk instead a primary one, it is because the categoryCode **"guest_disk1"** you set is for a secondary disk, following is the info of the price 112911
```
/SoftLayer_Product_Package/46/getItemPrices?objectMask=mask[id,locationGroupId,categories,item[id,capacity,description,keyName,itemCategory]]

{
        "id": 112911,
        "locationGroupId": 505,
        "categories": [
            {
                "categoryCode": "guest_disk1",
                "id": 82,
                "name": "Second Disk",
            }
        ],
        "item": {
            "capacity": "300",
            "description": "300 GB (LOCAL)",
            "id": 3890,
            "keyName": "GUEST_DISK_300_GB_LOCAL",
            "itemCategory": {
                "categoryCode": "guest_disk1",
                "id": 82,
                "name": "Second Disk",
            }
        }
    },
```

And if you review the item 3890 you will notice it is for disks from second to fifth position, it means the price 112911 can only be used to order second, third, fourth, or fifth disks and not for a first disk.

```
/SoftLayer_Product_Package/46/getItems?objectMask=mask[id,keyName,capacity,description,categories]

{
        "capacity": "300",
        "description": "300 GB (LOCAL)",
        "id": 3890,
        "keyName": "GUEST_DISK_300_GB_LOCAL",
        "categories": [
            {
                "categoryCode": "guest_disk1",
                "id": 82,
                "name": "Second Disk",
            },
            {
                "categoryCode": "guest_disk2",
                "id": 92,
                "name": "Third Disk",
            },
            {
                "categoryCode": "guest_disk4",
                "id": 116,
                "name": "Fifth Disk",
            },
            {
                "categoryCode": "guest_disk3",
                "id": 93,
                "name": "Fourth Disk",
            }
        ],
        "itemCategory": {
            "categoryCode": "guest_disk1",
            "id": 82,
            "name": "Second Disk",
        },
}
```
Since the price 112911 cannot be ordered to replace first disk I recommend you to use another price, as far I could see, primary disk can only be 25 or 100 GB only, and 150 GB if the VSI is into a dedicated host.

**Comment by allmightyspiff** [comment]
@acamacho82 I believe @edwardstudy is trying to upgrade his secondary drive from 100G to 300G, but instead is getting a 3rd drive of 300G.

Can you confirm what the correct way to upgrade a secondary disk from 100G->300G is?

**Comment by acamacho82** [comment]
Well, the payload that @edwardstudy  is sending is correct, at least it worked for me, the 2nd disk of my VSI was upgraded from 100 to 300 GB and a 3rd disk was not added.

**Comment by acamacho82** [comment]
@edwardstudy the way you are sending the upgrade request is correct, we are still investigating this behavior and any update will be posted in the ticket 67079537 internally so I recommend you to be aware of new updates

**Comment by edwardstudy** [comment]
Hi, @acamacho82. You could see the ticket about it(https://control.softlayer.com/support/tickets/67079537). this VSI had a disk issue last year and supports help us to fix that issue. I am not sure these operations caused my new disk could not to replace old one.

**Comment by allmightyspiff** [comment]
To close this out, it looks like the upgrade was placed correctly, but provisioning system was not able to edit the existing volume for some reason, so a new one was added instead.
