### ISSUE TITLE
Update lbaas bluemix docs

### ISSUE THREAD

**Issue by allmightyspiff** [softlayer/softlayer.github.io#138]
https://console.bluemix.net/docs/infrastructure/loadbalancer-service/apis.html#api-reference uses python/soap instead of the official softlayer python client, so we should update that example to fix this.

**Comment by acamacho82** [comment]
I think https://softlayer.github.io/python/lbaas/ has some examples that can be used as reference

**Comment by allmightyspiff** [comment]
https://github.com/IBM-Bluemix-Docs/loadbalancer-service/pull/5
