### ISSUE TITLE
Inconsistent doc for API keys

### ISSUE THREAD

**Issue by justin-fleming** [softlayer/softlayer.github.io#143]
The [getApiAuthenticationKeys page](https://sldn.softlayer.com/reference/services/SoftLayer_User_Customer_OpenIdConnect/getApiAuthenticationKeys/) says that the max number of API keys per user is 2 which is inconsistent with the [addApiAuthenticationKey page](https://sldn.softlayer.com/reference/services/SoftLayer_User_Customer/addApiAuthenticationKey/) which says the limit is one. I have observed that the limit is indeed one; when attempting to call addApiAuthenticationKey for a user that already has an API key, I got the following:
```
SoftLayerAPIError(SoftLayer_Exception_Public): Each user can only have a single API key.
```

**Comment by allmightyspiff** [comment]
https://sldn.softlayer.com/reference/services/SoftLayer_User_Customer_OpenIdConnect/getApiAuthenticationKeys/
now has the proper documentation.
