### ISSUE TITLE
Feedback for article - C Sharp

### ISSUE THREAD

**Issue by jpinterp** [softlayer/softlayer.github.io#146]
Feedback regarding: https://sldn.softlayer.com/article/c-sharp/

Yesterday I wrote a complaint that the wsdl tool was not compatible but I was wrong.  Turns out the tool forces  an old version of .NET which does not support TLS12.  By removing the wsdl.exe.config file, the tool used the latest version of .NET installed (4.6) and the tool created the files just fine.

I also said that PowerShell was not able to create a proxy as it too was not handling TLS12 correctly.  Here is the PowerShell equivalent of the sample above.  Please rename from .txt extension to .ps1.

Thanks,
  Jeff

[SoftLayer.txt](https://github.com/softlayer/softlayer.github.io/files/2971180/SoftLayer.txt)

**Comment by allmightyspiff** [comment]
hey jpinterp, sorry for taking so long to get to this issue.  I'm not really familiar with c-sharp or powershell, is any part of the c-sharp article outdated? Or were you just showing an example of how powershell handles web proxies ? I'm not clear if anything in that article needs to be changed or added.
