### ISSUE TITLE
Out of Date Documentation for the API

### ISSUE THREAD

**Issue by gokul-uf** [softlayer/softlayer.github.io#147]
Hi,
I am looking at the API docs from https://sldn.softlayer.com/reference/softlayerapi/. It seems like there are quite a few inconsistencies between the docs and the current API.

For example, there's no longer a service called `Search` and there are changes in the methods available as part of the `Ticket` service.

Could you let me know where the up-to-date docs are available?

FYI I'm using the softlayer-python API `v5.7.1`

Thanks

**Comment by allmightyspiff** [comment]
https://sldn.softlayer.com/reference/softlayerapi/ is updated weekly, and will be at most a day or two out of date.

The search service still exists. Which changes to the Ticket service do you not see?
