### ISSUE TITLE
Feedback for fog - Managing VSI's and Bare Metal servers  with fog-softlayer

### ISSUE THREAD

**Issue by sandratiffin** [softlayer/softlayer.github.io#156]
Feedback regarding: https://sldn.softlayer.com/fog/compute/

Is there a way to provision a VM and attach security group(s) to it using fog-softlayer? I'm not seeing one, and that is a problem.  (kitchen-softlayer uses fog-softlayer; I can provision an instance with kitchen-softlayer, but kitchen cannot ssh to it as the 'ssh_allow' security group is not attached to the VM).

**Comment by allmightyspiff** [comment]
Through the softlayer-fog library itself, I'm not sure. You might try opening an issue with https://github.com/fog/fog-softlayer for them to add support for that, although I'm not sure who is actively maintaining that project at the moment, if anyone. 

It looks like fog-softlayer supports making arbitrary api calls ( in https://github.com/fog/fog-softlayer/blob/master/lib/fog/softlayer/slapi.rb ), so you might be able to pass your new VMs Public Network Component's id to https://sldn.softlayer.com/reference/services/SoftLayer_Network_SecurityGroup/attachNetworkComponents/ so you can attach the security group after creation. 

From briefly looking over the source code for fog-softlayer, I think supporting creating a VM with a security group already in place would require some code changes.

https://sldn.softlayer.com/ruby/vsiSecGroups/ is an example of how to create a VSI with security groups in pure ruby, if that is any help.
