### ISSUE TITLE
"View Documentation" button leads to a 404 link

### ISSUE THREAD

**Issue by enebab** [softlayer/softlayer.github.io#160]
When you login to the portal:

https://cloud.ibm.com/classic/storage/objectstorage

There is a "View Documentation" button at the top right which leads to a 404 link when clicked.

Please fix the button with the correct link.  

Thank you.

**Comment by allmightyspiff** [comment]
per our slack conversation, https://cloud.ibm.com/classic/storage/objectstorage should link to cloud.ibm.com/docs/infrastructure/cloud-object-storage-infrastructure .
