### ISSUE TITLE
Openshift Object-Masks and using API Call for Tags.

### ISSUE THREAD

**Issue by DarienLowe** [softlayer/softlayer.github.io#164]
Feedback regarding: https://sldn.softlayer.com/article/object-masks/

Is it possible to do Object Masks of the content curated on the Openshift dashboard?

Specifically, I wanted to do a mask and api call to look at all of the tags from environments on the Openshift section.

I couldn't find any documentation on it, and I'm aware that it is a newer feature.

**Comment by allmightyspiff** [comment]
I don't know what information is on the openshift dashboard, so you will need to be more specific on what you are looking for.

If you just want tags of all your virtualGuests or hardware, you can do the following.

```
slcli -v --format=json call-api SoftLayer_Account getVirtualGuests --mask="mask[id,hostname,tagReferences[id,tag[name]]]"
Calling: SoftLayer_Account::getVirtualGuests(id=None, mask='mask[id,hostname,tagReferences[id,tag[name]]]', filter='{}', args=(), limit=None, offset=None))

    {
        "hostname": "fotest",
        "id": 61445229,
        "tagReferences": [
            {
                "id": 152986538,
                "tag": {
                    "name": "tagtest1"
                }
            },
            {
                "id": 152986540,
                "tag": {
                    "name": "tagtest2"
                }
            },
            {
                "id": 152986542,
                "tag": {
                    "name": "tagtest3"
                }
            }
        ]
    },
```
For hardware servers, just replace `getVirtualGuests` with `getHardware`

`SoftLayer_Account::getVirtualGuests` returns a  [Virtual_Guest[]](https://sldn.softlayer.com/reference/datatypes/SoftLayer_Virtual_Guest/) object, so you start with that as the base for the object mask. And select [Virtual_Guest->tagReferences](https://sldn.softlayer.com/reference/datatypes/SoftLayer_Virtual_Guest/#tagreferences), then select [Tag_Reference->tag](https://sldn.softlayer.com/reference/datatypes/SoftLayer_Tag_Reference/#tag) then finally [Tag->name](https://sldn.softlayer.com/reference/datatypes/SoftLayer_Tag/#name)

**Comment by allmightyspiff** [comment]
https://sldn.softlayer.com/python/tags.py/ also has a lot of good information on working with tags now.
