### ISSUE TITLE
Plans for Incorporating .NET Core SDK as part of Softlayer

### ISSUE THREAD

**Issue by clinton1994** [softlayer/softlayer.github.io#167]
Hi Team, 

With .NET Core on the rise in the dev community, do we have any plans to introduce its SDK as part of softlayer ?

Thanks

**Comment by allmightyspiff** [comment]
At the moment we don't have any plans for a .NET specific library. Mostly because there are not any .NET developers on the SLDN team currently.

If someone with .NET experience wants to create one I'd be happy to help put it on the softlayer github and get it made official though.

**Comment by clinton1994** [comment]
@allmightyspiff  , I can help get this kickstarted, let me know what is required
