### ISSUE TITLE
Add short vs php api examples in a single file

### ISSUE THREAD

**Issue by FernandoOjeda** [softlayer/softlayer.github.io#189]
Add short vs php api examples in a single file:

1. Get primary ip address record https://sldn.softlayer.com/php/primary_ip_address_record/.
2. Attach and Detach a Block Device to a Virtual_Guest https://sldn.softlayer.com/php/attach_detach/.
3. Month-to-date cost of a Virtual_Guest https://sldn.softlayer.com/php/monthtodate/.
4. ActivePrivatePort.php https://sldn.softlayer.com/php/ActivePrivatePort.php/.
5. ActivePublicPort.php https://sldn.softlayer.com/php/ActivePublicPort.php/.

**Comment by allmightyspiff** [comment]
once youve merged the examples into a single file, can you remove the old examples as well.
