### ISSUE TITLE
Feedback for go - get_all_billing_invoice_items.go

### ISSUE THREAD

**Issue by zxqw1541** [softlayer/softlayer.github.io#201]
Feedback regarding: https://sldn.softlayer.com/go/get_all_billing_invoice_items.go/

hi.
Thanks for the source.

I found wrong source.
---------------------------------------------------------------------------------
fmt.Printf("\n\nINVOICE ID: %d\t CREATE DATE: %s\t TYPE CODE: %s\n\n",
			invoice.Id, invoice.CreateDate, *invoice.TypeCode)
---------------------------------------------------------------------------------

It seems to be changed to this
---------------------------------------------------------------------------------
fmt.Printf("\n\nINVOICE ID: %d\t CREATE DATE: %s\t TYPE CODE: %s\n\n",
			*invoice.Id, invoice.CreateDate, *invoice.TypeCode)
---------------------------------------------------------------------------------

**Comment by allmightyspiff** [comment]
Fixed in https://github.com/softlayer/githubio_source/pull/426
