### ISSUE TITLE
Feedback for article - Authenticating to the SoftLayer API

### ISSUE THREAD

**Issue by markododa** [softlayer/softlayer.github.io#211]
Feedback regarding: https://sldn.softlayer.com/article/authenticating-softlayer-api/
function get_ims_token_password in the python script for ibm cloud user uses json.load instead of json.loads

**Comment by allmightyspiff** [comment]
I've removed that bit as there are easier ways to get a token for API calls now that don't involve getting the ims token specifically. The `access_token` provided by the IAM service will now work directly, which is nice.
