### ISSUE TITLE
Update the CDN APIs on different language examples

### ISSUE THREAD

**Issue by leibaogit** [softlayer/softlayer.github.io#232]
Since the old VDMS CDN (SoftLayer_Network_ContentDelivery) was sunset, but we can still the APIs present in the different language examples. In the mean while, the new CDN (SoftLayer_Network_CdnMarketplace) was GAed at 2017, but we can not see the new APIs in all languages. 

1. Remove the legacy CDN APIs
- GO
https://sldn.softlayer.com/go/cancel_cdn.go/
https://sldn.softlayer.com/go/get_cdn_list.go/
https://sldn.softlayer.com/go/place_order_cdn.go/

- Perl
https://sldn.softlayer.com/perl/place_order_cdn.pl/

- PHP
https://sldn.softlayer.com/php/PlaceOrderCDN.php/

- Ruby
https://sldn.softlayer.com/ruby/cancel_cdn.rb/
https://sldn.softlayer.com/ruby/place_order_cdn.rb/

2. Add new CDN APIs for all languages.

**Comment by allmightyspiff** [comment]
We do have a few examples on the CdnMarketplace APi: 
Python - https://sldn.softlayer.com/python/cdn_network.py/
Golang - https://sldn.softlayer.com/go/CDN_services.go/
Ruby - https://sldn.softlayer.com/ruby/cdn_network.rb/

I'm not an expert on the CDN stuff, so if those need updating or anything, please let me know.

In the mean time, well remove those listed examples.

Thanks.

**Comment by allmightyspiff** [comment]
Fixed in https://github.com/softlayer/githubio_source/pull/425
