### ISSUE TITLE
Unable to get any value from https://api.softlayer.com/rest/v3.1/SoftLayer_Product_Package/1123/getActivePresets

### ISSUE THREAD

**Issue by emarcora** [softlayer/softlayer.github.io#285]
Hi, on interrogating this API for VIRTUAL_SERVER_FOR_VPC I'm getting an empty array as response.

For similar service (PUBLIC_CLOUD_SERVER), instead, I'm getting the expected response 

[
    {
        "description": "AC2.8x60x25",
        "id": 861,
        "isActive": "1",
        "keyName": "AC2_8X60X25",
        "name": "AC2.8x60x25",
        "packageId": 835
    },
    {
        "description": "AC2.8x60x100",
        "id": 863,
        "isActive": "1",
        "keyName": "AC2_8X60X100",
        "name": "AC2.8x60x100",
        "packageId": 835
    }, ...]

Am I missing something? My goal is to get programmatically prices for virtual server for vpc service as I did for Virtual service for Classic. Thank you in advance!

**Comment by allmightyspiff** [comment]
api.softlayer.com is really only for Classic Infrastructure services. https://cloud.ibm.com/docs/vpc is where you will want to start for VPC related things
