### ISSUE TITLE
SoftLayer_Hardware_Server API serivce: SoftLayer_Hardware_Server  is lack of bios/ipmi firmware update info

### ISSUE THREAD

**Issue by jujuv587** [softlayer/softlayer.github.io#340]
SoftLayer_Hardware_Server API serivce: SoftLayer_Hardware_Server  is lack of bios/ipmi firmware update info.

Hi IBM Cloud, when a baremetal needs a critical firmware update on bios/ipmi, it only shows from UI page.

<img width="1257" alt="Screenshot 2024-04-05 at 4 07 29 PM" src="https://github.com/softlayer/softlayer.github.io/assets/37676648/3f18748a-4589-4fcf-9cfd-46f5aaa3b245">

I’m developing an SL API service automation to confirm if a firmware has critical updates to do before sending power off commands and perform firmware updates. 

I looked into

https://sldn.softlayer.com/reference/services/SoftLayer_Hardware_Server/

However, the service only contains firmwareUpdate functionalities without providing the current version/up-to-date version/firmware Update status info.

I also looked into SoftLayer_Hardware_Component_Firmware data type returned and found the create/build dates, isQualified, serverity info, version is not well recorded in terms of getting current/target version and lack of explanation on the document link.

Could you please let me know if there’s a way in softlayer API that can provide firmware update required info or how SoftLayer_Hardware_Component_Firmware data type attributes recorded?

Thanks

**Comment by allmightyspiff** [comment]
Hello,

Sorry for the delay on answering this. [SoftLayer_Hardware_Component::hasUpgradeableFirmware](https://sldn.softlayer.com/reference/datatypes/SoftLayer_Hardware_Component/#hasUpgradeableFirmware) is the property you are looking for.

API response would look something like this:
```
slcli --format=json call-api SoftLayer_Hardware_Server getObject --id=3220256 --mask="mask[id,hostname,activeComponents[id,revision,componentRevision,hasUpgradeableFirmware]]"
{
  "hostname": "fra02-ocp-virt",
  "id": 3220256,
  "activeComponents": [
    {
      "componentRevision": "TN05",
      "hasUpgradeableFirmware": true,
      "id": 19906770,
      "revision": {
        "firmwareVersionId": 110505,
        "hardwareComponentId": 19906770,
        "id": 13404668,
        "revision": "TN05"
      }
    },
    {
      "componentRevision": null,
      "hasUpgradeableFirmware": false,
      "id": 13120803,
      "revision": {
        "firmwareVersionId": null,
        "hardwareComponentId": 13120803,
        "id": 5768905
      }
    },
    {
      "componentRevision": " 7.00",
      "hasUpgradeableFirmware": true,
      "id": 22811766,
      "revision": {
        "firmwareVersionId": 186238,
        "hardwareComponentId": 22811766,
        "id": 16507548,
        "revision": " 7.00"
      }
    }
  ]
}
```

Hope that helps.
