### ISSUE TITLE
SoftLayer_Account::getVpcVirtualGuests returns a blank array

### ISSUE THREAD

**Issue by jinzongna** [softlayer/softlayer.github.io#353]
https://sldn.softlayer.com/reference/services/SoftLayer_Account/getVpcVirtualGuests/
I can see VPC instance from IBM Cloud Portal, but use above API returns a blank array.
A similar API getVirtualGuests works fine for me.

**Comment by allmightyspiff** [comment]
This API is actually for an older (and since deprecated) SoftLayer virtual private cloud offering, not for the Ibmcloud VPC.

I think you'll need to reference https://cloud.ibm.com/apidocs/vpc/latest for anything VPC related specifically. Hope this helps.
