### ISSUE TITLE
Broken Link in tools (salt-cloud)

### ISSUE THREAD

**Issue by sudorandom** [softlayer/softlayer.github.io#81]
Feedback regarding: https://softlayer.github.io/tools/

The 'Virtual Guests' link under the Salt-Cloud section is broken: https://docs.saltstack.com/en/develop/ref/clouds/all/salt.cloud.clouds.softlayer.html

I think the correct URL is https://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.softlayer.html

**Comment by greyhoundforty** [comment]
Pull request with updated link created
