### ISSUE TITLE
Enhancement Request: Python Examples for User managment

### ISSUE THREAD

**Issue by paulmcgrail** [softlayer/softlayer.github.io#83]
<p align="center">
  <b>Samples/Enhancements Requests</b><br> 
1. Audit Report: If a user has not logged on in 90 Day, mark account as inactive and send email for continued business need
2. Access Log report: The Access Log for the account cannot be downloaded from the Portal
3. Account Validation: A Simple report to pull all email addresses and compares them against an external LDAP server, Users not found could be disabled disabled
4. Simple inventory report by user that could be run nightly vs the Monthly Invoice which does not track back to the user.

These examples would go a long way in helping the account managers track usage, security and compliance.  I think these would be a good compliment to the existing hardware examples for account management.

Thanks for the awesome work on these tools

**Comment by allmightyspiff** [comment]
So, 4 years later I finally decided to resolve this issue, sorry for the wait.

There are already a few pyhton examples for user management here: [User Examples](https://sldn.softlayer.com/tags/users/)
But I wrote up an article that should hopefully explain the User_Customer class in a bit more detail. The examples you wanted are a bit too involved I think to make a good example for SLDN, but hopefully the [User Article](https://sldn.softlayer.com/article/Users/) will clear up how to get the information you would need for them.
