### ISSUE TITLE
Feedback for python - Place quote order

### ISSUE THREAD

**Issue by owhc** [softlayer/softlayer.github.io#93]
Feedback regarding: https://softlayer.github.io/python/order_quote/

Not really related to order_quote function. but related to Bluemix portal. Any other post could let us report bugs?

[REPORT BUG]
Click the link: "https://console.ng.bluemix.net/catalog/infrastructure/monthly_public_virtual/" , always redirect to "https://console.ng.bluemix.net/catalog/"
BMS and VM of hourly and monthly, got the same results , redirect to "https://console.ng.bluemix.net/catalog/"

**Comment by allmightyspiff** [comment]
https://console.ng.bluemix.net/catalog/infrastructure/virtual-server-monthly/ is the proper link I believe.


This project is just for examples on how to use the SoftLayer API, issues with the bluemix console portal should be reported in a ticket created in the portal itself.


Thanks.
