### ISSUE TITLE
Feedback for python - How do get storage capacity of Cloud Object Storage - S3 API

### ISSUE THREAD

**Issue by owhc** [softlayer/softlayer.github.io#96]
Hi there, 

I checked the API reference. There is a SoftLayer_Network_Storage_Hub_Cleversafe_Account services. However, I always got exception : 
`Traceback (most recent call last):
  File "bmxi_s3_stg_usage.py", line 11, in <module>
    getS3StgUsage()
  File "bmxi_s3_stg_usage.py", line 7, in getS3StgUsage
    endpoints = client['Network_Storage_Hub_Cleversafe_Account'].getEndpoints()
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/API.py", line 392, in call_handler
    return self(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/API.py", line 360, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/API.py", line 263, in call
    return self.transport(request)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/transports.py", line 195, in __call__
    raise _ex(ex.faultCode, ex.faultString)
SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception): Object does not exist to execute method on. (SoftLayer_Network_Storage_Hub_Cleversafe_Account::getEndpoints)`

Version: SoftLayer (5.2.4) , Python 2.7.0
Would you please advise? Thank you.

**Comment by greyhoundforty** [comment]
Are you making sure to specify the Cloud Object Storage S3 account in the call? That is needed or else the method for the service does not return any results. 

```
curl -s "https://$SOFTLAYER_USERNAME:$SOFTLAYER_API_KEY@api.softlayer.com/rest/v3/SoftLayer_Network_Storage_Hub_Cleversafe_Account/getEndpoints" | pmj
{
    "code": "SoftLayer_Exception",
    "error": "Object does not exist to execute method on. (SoftLayer_Network_Storage_Hub_Cleversafe_Account::getEndpoints)"
}

curl -s "https://$SOFTLAYER_USERNAME:$SOFTLAYER_API_KEY@api.softlayer.com/rest/v3/SoftLayer_Network_Storage_Hub_Cleversafe_Account/15418877/getEndpoints" | pmj
[
    {
        "region": "us-geo",
        "type": "public",
        "url": "s3-api.us-geo.objectstorage.softlayer.net"
    },

curl -s "https://$SOFTLAYER_USERNAME:$SOFTLAYER_API_KEY@api.softlayer.com/rest/v3/SoftLayer_Network_Storage_Hub_Cleversafe_Account/15418877/getCapacityUsage" | pmj
9586153789
```

**Comment by owhc** [comment]
Thanks! Solved!

**Comment by owhc** [comment]
BTW, how do I retrieve S3 storage account via API?

**Comment by greyhoundforty** [comment]
Are you looking for the specific account information or to get a list of the Cloud Object Storage (S3) accounts? 

To get information about your specific account you can use:
```
SoftLayer_Network_Storage_Hub_Cleversafe_Account/ACCOUNT_ID/getAccount
```

I am not sure on the best way to get all the S3 accounts under your entire SoftLayer account. When I was providing the previous example I actually went in via the portal to get the COS (S3) account ID. Perhaps @allmightyspiff would know of the best way to do this.

**Comment by allmightyspiff** [comment]
https://sldn.softlayer.com/go/CDN_services.go/ has some Go examples on how to interact with the S3 CDN service.

Most of the API examples for S3 CDN will be found on the IBM cloud docs site now though: https://cloud.ibm.com/docs/CDN?topic=CDN-cdn-api-referenc
