### ISSUE TITLE
Feedback for python - Order a Netscaler

### ISSUE THREAD

**Issue by jm-paulin** [softlayer/softlayer.github.io#98]
Feedback regarding: https://softlayer.github.io/python/orderNetscaler/

Hi, 

How do we lookup the prices Id and packages Id ?

Thanks

JM

**Comment by allmightyspiff** [comment]
https://softlayer.github.io/python/list_packages/

is a decent example of how to iterate through packages and the prices inside of them.

Hopefully that helps.
