### ISSUE TITLE
How to get a Vyatta default Group number by calling Softlayer API?

### ISSUE THREAD

**Issue by penzhan8451** [softlayer/softlayer.github.io#99]
hello,

I want to call Softlayer API to get vyatta group nubmer which was defined in SL (SL console->network->Gateway Appliances, then you can see 'Group Number' field).  How can I do it? Is there any example? 

![image](https://user-images.githubusercontent.com/10585564/28958295-5db6ec42-7928-11e7-9601-d7b4cb90b006.png)

Thanks very much.

**Comment by acamacho82** [comment]
It is a very old issue, I'm not sure if you still requires this information (maybe not), anyway I would like to let you know there were added some examples on November 23 of the same year. I hope you were able to review them before this comment.

https://softlayer.github.io/python/get_gateway_details.py/
https://softlayer.github.io/java/GetGatewayDetails.java/
https://softlayer.github.io/go/get_gateway_details.go/
